export enum FieldEngineering {
  Civil = "Engenharia Civil",
  Mecanica = "Engenharia Mecanica" ,
  Eletrica = "Engenharia Eletrica",
  Eletronica = "Engenharia Eletronica",
  Producao = "Engenharia de Producao",
  Computacao = "Engenharia da Computacao",
  Quimica = "Engenharia Quimica",
  Ambiental = "Engenharia Ambiental",
  Alimentos = "Engenharia de Alimentos",
  Agronoma = "Engenharia Agronomica",
  Florestal = "Engenharia Florestal",
  Petroleo = "Engenharia de Petroleo",
  Biomedica = "Engenharia Biomedica",
  Telecomunicacoes = "Engenharia de Telecomunicacoes",
  Naval = "Engenharia Naval",
  Aeronautica = "Engenharia Aeronautica",
  Nuclear = "Engenharia Nuclear",
  Materiais = "Engenharia de Materiais",
  Sanitaria = "Engenharia Sanitaria" 
}